server:
  port: 9192
  error:
    include-message: always

spring:
  datasource:
    url: ${db_url}
    username: ${db_username}
    password: ${db_password}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

