server:
  port: 9192
  error:
    include-message: always

spring:
  datasource:
    url: ${env.DB_URL}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

